lockpick:
  item:
    material: WOOD_AXE
    name: "LockPick"
    lore:
      - "The lockpick o:"
  ratio: 0.25
  damage: 2.0
  successMessage: "&aYou've cracked the door open!"
  failMessage: "&cYour cracking attempt has failed!"
  crackSound:
    effect: "ENTITY_ITEM_PICKUP"
    v: 1
    v1: 1
  damageSound:
    effect: "BLOCK_ANVIL_HIT"
    v: 1
    v1: 1
apartment:
  auto-evict: true
  default_price: 100
  forRentSignPlacementTrigger: "[Rent]"
  forRentSignContent:
    - "[Rent]"
    - "Price: %price%"
    - ""
    - ""
  rentedSignContent:
    - "[Rented]"
    - "Owner: %owner%"
    - ""
    - ""
  allowed_doors:
    - "DARK_OAK_DOOR"
    - "BIRCH_DOOR"
    - "WOODEN_DOOR"
    - "SPRUCE_DOOR"
    - "JUNGLE_DOOR"
    - "ACACIA_DOOR"
    - "IRON_DOOR_BLOCK"